#!/usr/bin/env bash
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  echo "Run as: source ./activate"
  exit 1
fi
source "$(dirname "${BASH_SOURCE[0]}")/venv/bin/activate"
echo "Venv active: $(python --version)"
